Support Yara Scan Flags
Hugal31/yara-rust pull request #8
Opened 2020-08-28 23:56 UTC by rc-grey

Simply added support for Yara scan flags, exposed via the Rules object.

2020-08-31 07:17 UTC, Hugal31 requested changes

2020-08-31 07:17 UTC, Hugal31 commented on src/rules.rs
> +pub const SCAN_FLAGS_REPORT_RULES_NOT_MATCHING: i32 = 16;
I'd prefer to import the flags with bindgen, and re-export them from yara_src.

2020-08-31 08:02 UTC, Hugal31 commented
It would also be great if you could add a test for your use case.

2020-09-07 16:46 UTC, rc-grey commented
This may address your other issue regarding linking options, not sure.

2020-09-07 16:54 UTC, Hugal31 approved these changes

2020-09-07 16:57 UTC, rc-grey commented
Do you mind making a release with this?

2020-09-07 17:24 UTC, Hugal31 commented
I don't know why Travis isn't showing up here but https://travis-ci.org/github/Hugal31/yara-rust/jobs/724992831

2020-09-07 17:38 UTC, rc-grey commented
Sorry about that - fixed.

2020-09-08 07:55 UTC, merged